import {
	ZAnnotationListQuery,
	ZBookmark,
	ZCreateBookmarkDTO,
	ZBookAsset,
	ZCreateCatalogBookDTO,
	ZCreateHighlightDTO,
	ZCreateLibraryBookDTO,
	ZCreateNoteDTO,
	ZHighlight,
	ZLibraryBookmarkIDParams,
	ZLibraryBookmarksResponse,
	ZLibraryBookIDParams,
	ZLibraryCatalogListResponse,
	ZLibraryCatalogCreateResponse,
	ZLibraryDeleteResponse,
	ZLibraryHighlightIDParams,
	ZLibraryHighlightsResponse,
	ZLibraryListQuery,
	ZLibraryNoteIDParams,
	ZLibraryNotesResponse,
	ZLibraryBooksListResponse,
	ZNote,
	ZReadingState,
	ZReadingStatePathParams,
	ZUpdateBookmarkDTO,
	ZUpdateHighlightDTO,
	ZUpdateLibraryBookDTO,
	ZUpdateNoteDTO,
	ZUploadBookAssetDTO,
	ZUpsertReadingStateDTO,
	ZUserLibraryBook,
} from '@kern/zod'
import { initContract } from '@ts-rest/core'
import { failResponses, getSecurityMetadata } from '../utils.js'

const c = initContract()
const metadata = getSecurityMetadata({ security: true, securityType: 'bearerOrCookie' })

export const libraryContract = c.router({
	createCatalogBook: {
		summary: 'Create catalog book',
		description: 'Create a catalog-level book record.',
		path: '/api/v1/library/catalog/books',
		method: 'POST',
		body: ZCreateCatalogBookDTO,
		responses: {
			201: ZLibraryCatalogCreateResponse,
			...failResponses,
		},
		metadata,
	},
	listCatalogBooks: {
		summary: 'List catalog books',
		description: 'List catalog books with pagination.',
		path: '/api/v1/library/catalog/books',
		method: 'GET',
		query: ZLibraryListQuery,
		responses: {
			200: ZLibraryCatalogListResponse,
			...failResponses,
		},
		metadata,
	},
	uploadAsset: {
		summary: 'Upload book asset',
		description: 'Upload and attach a file asset to a catalog book.',
		path: '/api/v1/library/assets/upload',
		method: 'POST',
		body: ZUploadBookAssetDTO,
		responses: {
			201: ZBookAsset,
			...failResponses,
		},
		metadata,
	},
	upsertLibraryBook: {
		summary: 'Upsert library book',
		description: 'Create or update current user library entry for a catalog book.',
		path: '/api/v1/library/books',
		method: 'POST',
		body: ZCreateLibraryBookDTO,
		responses: {
			201: ZUserLibraryBook,
			...failResponses,
		},
		metadata,
	},
	listLibraryBooks: {
		summary: 'List library books',
		description: 'List authenticated user library books.',
		path: '/api/v1/library/books',
		method: 'GET',
		query: ZLibraryListQuery,
		responses: {
			200: ZLibraryBooksListResponse,
			...failResponses,
		},
		metadata,
	},
	updateLibraryBook: {
		summary: 'Update library book',
		description: 'Update authenticated user library book fields.',
		path: '/api/v1/library/books/:id',
		method: 'PATCH',
		pathParams: ZLibraryBookIDParams,
		body: ZUpdateLibraryBookDTO,
		responses: {
			200: ZUserLibraryBook,
			...failResponses,
		},
		metadata,
	},
	deleteLibraryBook: {
		summary: 'Delete library book',
		description: 'Soft delete a user library book entry.',
		path: '/api/v1/library/books/:id',
		method: 'DELETE',
		pathParams: ZLibraryBookIDParams,
		responses: {
			200: ZLibraryDeleteResponse,
			...failResponses,
		},
		metadata,
	},
	getReadingState: {
		summary: 'Get reading state',
		description: 'Get reading state by mode for a library book.',
		path: '/api/v1/library/books/:id/reading-states/:mode',
		method: 'GET',
		pathParams: ZReadingStatePathParams,
		responses: {
			200: ZReadingState,
			...failResponses,
		},
		metadata,
	},
	upsertReadingState: {
		summary: 'Upsert reading state',
		description: 'Create or update reading state with conflict semantics.',
		path: '/api/v1/library/books/:id/reading-states/:mode',
		method: 'PUT',
		pathParams: ZReadingStatePathParams,
		body: ZUpsertReadingStateDTO,
		responses: {
			200: ZReadingState,
			...failResponses,
		},
		metadata,
	},
	listHighlights: {
		summary: 'List highlights',
		description: 'List highlights for a library book.',
		path: '/api/v1/library/books/:id/highlights',
		method: 'GET',
		pathParams: ZLibraryBookIDParams,
		query: ZAnnotationListQuery,
		responses: {
			200: ZLibraryHighlightsResponse,
			...failResponses,
		},
		metadata,
	},
	createHighlight: {
		summary: 'Create highlight',
		description: 'Create highlight for a library book.',
		path: '/api/v1/library/books/:id/highlights',
		method: 'POST',
		pathParams: ZLibraryBookIDParams,
		body: ZCreateHighlightDTO,
		responses: {
			201: ZHighlight,
			...failResponses,
		},
		metadata,
	},
	updateHighlight: {
		summary: 'Update highlight',
		description: 'Update a highlight.',
		path: '/api/v1/library/highlights/:highlightId',
		method: 'PATCH',
		pathParams: ZLibraryHighlightIDParams,
		body: ZUpdateHighlightDTO,
		responses: {
			200: ZHighlight,
			...failResponses,
		},
		metadata,
	},
	deleteHighlight: {
		summary: 'Delete highlight',
		description: 'Soft-delete a highlight.',
		path: '/api/v1/library/highlights/:highlightId',
		method: 'DELETE',
		pathParams: ZLibraryHighlightIDParams,
		responses: {
			200: ZLibraryDeleteResponse,
			...failResponses,
		},
		metadata,
	},
	listBookmarks: {
		summary: 'List bookmarks',
		description: 'List bookmarks for a library book.',
		path: '/api/v1/library/books/:id/bookmarks',
		method: 'GET',
		pathParams: ZLibraryBookIDParams,
		query: ZAnnotationListQuery,
		responses: {
			200: ZLibraryBookmarksResponse,
			...failResponses,
		},
		metadata,
	},
	createBookmark: {
		summary: 'Create bookmark',
		description: 'Create a bookmark for a library book.',
		path: '/api/v1/library/books/:id/bookmarks',
		method: 'POST',
		pathParams: ZLibraryBookIDParams,
		body: ZCreateBookmarkDTO,
		responses: {
			201: ZBookmark,
			...failResponses,
		},
		metadata,
	},
	updateBookmark: {
		summary: 'Update bookmark',
		description: 'Update a bookmark.',
		path: '/api/v1/library/bookmarks/:bookmarkId',
		method: 'PATCH',
		pathParams: ZLibraryBookmarkIDParams,
		body: ZUpdateBookmarkDTO,
		responses: {
			200: ZBookmark,
			...failResponses,
		},
		metadata,
	},
	deleteBookmark: {
		summary: 'Delete bookmark',
		description: 'Soft-delete a bookmark.',
		path: '/api/v1/library/bookmarks/:bookmarkId',
		method: 'DELETE',
		pathParams: ZLibraryBookmarkIDParams,
		responses: {
			200: ZLibraryDeleteResponse,
			...failResponses,
		},
		metadata,
	},
	listNotes: {
		summary: 'List notes',
		description: 'List notes for a library book.',
		path: '/api/v1/library/books/:id/notes',
		method: 'GET',
		pathParams: ZLibraryBookIDParams,
		query: ZAnnotationListQuery,
		responses: {
			200: ZLibraryNotesResponse,
			...failResponses,
		},
		metadata,
	},
	createNote: {
		summary: 'Create note',
		description: 'Create a note for a library book.',
		path: '/api/v1/library/books/:id/notes',
		method: 'POST',
		pathParams: ZLibraryBookIDParams,
		body: ZCreateNoteDTO,
		responses: {
			201: ZNote,
			...failResponses,
		},
		metadata,
	},
	updateNote: {
		summary: 'Update note',
		description: 'Update a note.',
		path: '/api/v1/library/notes/:noteId',
		method: 'PATCH',
		pathParams: ZLibraryNoteIDParams,
		body: ZUpdateNoteDTO,
		responses: {
			200: ZNote,
			...failResponses,
		},
		metadata,
	},
	deleteNote: {
		summary: 'Delete note',
		description: 'Soft-delete a note.',
		path: '/api/v1/library/notes/:noteId',
		method: 'DELETE',
		pathParams: ZLibraryNoteIDParams,
		responses: {
			200: ZLibraryDeleteResponse,
			...failResponses,
		},
		metadata,
	},
})
